import types from './types';

const attributesByTypes = {
  [types.STARSHIPS]: [
    'name',
    'MGLT',
    'cargo_capacity',
    'consumables',
    'cost_in_credits',
    'crew',
    'hyperdrive_rating',
    'length',
    'manufacturer',
    'max_atmosphering_speed',
    'model',
    'passengers',
    'starship_class',
  ],
  [types.VEHICLES]: [
    'name',
    'cargo_capacity',
    'consumables',
    'cost_in_credits',
    'crew',
    'length',
    'manufacturer',
    'max_atmosphering_speed',
    'model',
    'passengers',
    'vehicle_class',
  ],
  [types.PEOPLE]: [
    'name',
    'birth_year',
    'eye_color',
    'gender',
    'hair_color',
    'height',
    'mass',
    'skin_color',
  ],
  [types.SPECIES]: [
    'name',
    'average_height',
    'average_lifespan',
    'classification',
    'designation',
    'eye_colors',
    'hair_colors',
    'language',
  ],
  [types.PLANETS]: [
    'name',
    'climate',
    'diameter',
    'gravity',
    'orbital_period',
    'population',
    'rotation_period',
    'surface_water',
    'terrain',
  ],
  [types.FILMS]: [
    'title',
    'director',
    'episode_id',
    'opening_crawl',
    'producer',
    'release_date',
  ],
};

export default attributesByTypes;
